### ISSUE TITLE
x-ratelimit-remaining error

### ISSUE THREAD

**Issue by lee-schlesinger** [singer-io/tap-frontapp#2]
Copy of issue post at https://github.com/bytecodeio/tap-frontapp/issues/1 –

Every time I try to move data from Front with Stitch I get an `x-ratelimit-remaining` error. Here's a sample log:

```2019-01-30 16:28:13,802Z   main - INFO Running tap-frontapp version 1.0.3 and target-stitch version 1.8.1
2019-01-30 16:28:13,866Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-frontapp --config /tmp/tap_discover_config.json --discover
2019-01-30 16:28:14,060Z   main - INFO Tap exited normally.
2019-01-30 16:28:14,061Z   main - INFO Saving list of discovered streams
2019-01-30 16:28:14,144Z   main - INFO Saving structure of stream team_table
2019-01-30 16:28:14,283Z   main - INFO Getting list of selected properties
2019-01-30 16:28:14,304Z   main - INFO Starting tap: tap-env/bin/tap-frontapp --config /tmp/tap_config.json --properties /tmp/properties.json --catalog /tmp/catalog.json --state /tmp/tap_state.json
2019-01-30 16:28:14,306Z   main - INFO Starting target: target-env/bin/target-stitch --config /tmp/target_config.json
2019-01-30 16:28:14,477Z    tap - INFO metric: team_table 
2019-01-30 16:28:14,477Z    tap - INFO start_date: 2019-01-24T05:00:00+00:00 
2019-01-30 16:28:14,477Z    tap - INFO end_date: 2019-01-30T00:00:00+00:00 
2019-01-30 16:28:14,477Z    tap - INFO last_date: 2019-01-24T05:00:00+00:00 
2019-01-30 16:28:14,478Z    tap - INFO ut_current_date: 1548306000 
2019-01-30 16:28:14,478Z    tap - INFO ut_next_date: 1548392400 
2019-01-30 16:28:14,478Z    tap - INFO Metrics query - metric: team_table start_date: 1548306000 end_date: 1548392400 
2019-01-30 16:28:14,561Z target - INFO Using Stitch import URL https://api.stitchdata.com/v2/import/batch
2019-01-30 16:28:17,028Z    tap - INFO HTTP request to "analytics" endpoint took 2.549s, returned status code 401
2019-01-30 16:28:17,029Z    tap - INFO "daily_aggregated_metric" job took 2.6s, ended with status "failed"
2019-01-30 16:28:17,029Z    tap - CRITICAL 'x-ratelimit-remaining'
2019-01-30 16:28:17,030Z    tap - Traceback (most recent call last):
2019-01-30 16:28:17,030Z    tap -   File "tap-env/bin/tap-frontapp", line 11, in <module>
2019-01-30 16:28:17,030Z    tap -     sys.exit(main())
2019-01-30 16:28:17,030Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 225, in wrapped
2019-01-30 16:28:17,030Z    tap -     return fnc(*args, **kwargs)
2019-01-30 16:28:17,030Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_frontapp/__init__.py", line 85, in main
2019-01-30 16:28:17,030Z    tap -     sync(atx)
2019-01-30 16:28:17,030Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_frontapp/__init__.py", line 71, in sync
2019-01-30 16:28:17,030Z    tap -     streams.sync_selected_streams(atx)
2019-01-30 16:28:17,030Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_frontapp/streams.py", line 224, in sync_selected_streams
2019-01-30 16:28:17,030Z    tap -     sync_metrics(atx, 'team_table')
2019-01-30 16:28:17,030Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_frontapp/streams.py", line 211, in sync_metrics
2019-01-30 16:28:17,030Z    tap -     sync_metric(atx, metric, incremental_range, ut_current_date, ut_next_date)
2019-01-30 16:28:17,030Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_frontapp/streams.py", line 87, in sync_metric
2019-01-30 16:28:17,031Z    tap -     data = get_metric(atx, metric, start_date, end_date)
2019-01-30 16:28:17,031Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff.py", line 286, in retry
2019-01-30 16:28:17,031Z    tap -     ret = target(*args, **kwargs)
2019-01-30 16:28:17,031Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff.py", line 286, in retry
2019-01-30 16:28:17,031Z    tap -     ret = target(*args, **kwargs)
2019-01-30 16:28:17,031Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/ratelimit/decorators.py", line 113, in wrapper
2019-01-30 16:28:17,031Z    tap -     return func(*args, **kargs)
2019-01-30 16:28:17,031Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/ratelimit/decorators.py", line 80, in wrapper
2019-01-30 16:28:17,031Z    tap -     return func(*args, **kargs)
2019-01-30 16:28:17,031Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_frontapp/streams.py", line 75, in get_metric
2019-01-30 16:28:17,031Z    tap -     'end': end_date, 'metrics[]':metric}, endpoint='analytics')
2019-01-30 16:28:17,031Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_frontapp/http.py", line 85, in get
2019-01-30 16:28:17,031Z    tap -     return self.request('get', path, **kwargs)
2019-01-30 16:28:17,031Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff.py", line 286, in retry
2019-01-30 16:28:17,031Z    tap -     ret = target(*args, **kwargs)
2019-01-30 16:28:17,032Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_frontapp/http.py", line 66, in request
2019-01-30 16:28:17,032Z    tap -     self.calls_remaining = int(response.headers['X-Ratelimit-Remaining'])
2019-01-30 16:28:17,032Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/structures.py", line 52, in __getitem__
2019-01-30 16:28:17,032Z    tap -     return self._store[key.lower()][1]
2019-01-30 16:28:17,032Z    tap - KeyError: 'x-ratelimit-remaining'
2019-01-30 16:28:17,051Z target - INFO Exiting normally
2019-01-30 16:28:17,080Z   main - INFO Target exited normally with status 0
2019-01-30 16:28:17,081Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "'x-ratelimit-remaining'". Target succeeded.
```
When I inquired of the support team at Front, they said:

Looking at the extraction log, I see this line closely preceding the error:

2019-01-30 16:28:14,561Z target - INFO Using Stitch import URL https://api.stitchdata.com/v2/import/batch

api.stitchdata.com is not the URL of the Front public API, so I think that you're getting the ratelimiting error from a source other than Front.  Checking the logs again during that time period shows no access attempts by your team, and we do log all 429 rate limit errors.

**Comment by dylan-stitch** [comment]
The `2019-01-30 16:28:17,028Z    tap - INFO HTTP request to “analytics” endpoint took 2.549s, returned status code 401` line indicates that the tap is receiving a 401 error from Front's `Analytics` endpoint.

This can stem from insufficient permissions to access Front's API, especially if the authorizing account is not subscribed to a sufficient Front plan to access their API.

**Comment by lee-schlesinger** [comment]
The issue was caused by an invalid API token. The error message is misleading, but I can close the issue.
